#+title:      wsl2 clock is out of sync with windows
#+date:       [2023-12-09 Sat 20:09]
#+filetags:   :freshsetup:wsl:
#+identifier: 20231209T200922
#+STARTUP:    overview

Having this problem -
https://stackoverflow.com/questions/65086856/wsl2-clock-is-out-of-sync-with-windows

run this in powershell to confirm it:

#+begin_src bash
  Get-Date; wsl date
#+end_src

Solution is to run =sudo hwclock -s= command. It will sync the time.

But I don want to run it manually each time. I will make a script that runs
this command and put it in =.bashrc= so it automatically runs the script each
time I launch wsl. Should be enough?

[2023-12-10 Sun] sudo hwclock -s is not an option.. it does not always work
when I run it.

So there is another solution described here -
https://github.com/microsoft/WSL/issues/8204

tried to make a script for that. [[file:~/GIT/dotfiles/freshsetup/timesync.sh]]

* shutdown solution [2023-11-26 Sun]

clock out of sync - check this -
https://stackoverflow.com/questions/65086856/wsl2-clock-is-out-of-sync-with-windows

#+begin_src bash
  arvy@DESKTOP-AUDMJ7D:~$ timedatectl
                 Local time: Sun 2023-11-26 01:49:02 EET
             Universal time: Sat 2023-11-25 23:49:02 UTC
                   RTC time: Tue 2023-11-28 10:24:52
                  Time zone: Europe/Vilnius (EET, +0200)
  System clock synchronized: no
                NTP service: inactive
            RTC in local TZ: no
  arvy@DESKTOP-AUDMJ7D:~$ hwclock -s
  hwclock: Cannot access the Hardware Clock via any known method.
  hwclock: Use the --verbose option to see the details of our search for an access method.
  arvy@DESKTOP-AUDMJ7D:~$ sudo hwclock -s
  [sudo] password for arvy:
  arvy@DESKTOP-AUDMJ7D:~$ timedatectl
                 Local time: Tue 2023-11-28 12:25:24 EET
             Universal time: Tue 2023-11-28 10:25:24 UTC
                   RTC time: Tue 2023-11-28 10:25:24
                  Time zone: Europe/Vilnius (EET, +0200)
  System clock synchronized: no
                NTP service: inactive
            RTC in local TZ: no
  arvy@DESKTOP-AUDMJ7D:~$
#+end_src

shutdown wsl if its stuck for some reason - powershell administrator
then type - "taskkill /f /im wslservice.exe"

sudo hwclock -s - should work also, but did not work for me.

to fix the clock:
wsl --shutdown
wsl

wsl --list --online
wsl --install -d ubuntu
wsl --list --all

To reinstall ubuntu on windows 11:
wsl --list --all
wsl --unregister Ubuntu
wsl --shutdown
wsl --install -d ubuntu
sudo apt update
sudo apt upgrade

Emacs installed simple way, but no gui
wsl --update
wsl --shutdown
then start wsl again somehow, by launching wsl apps in the windows taskbar
emacs in ubuntu
launched!!!
no need of any X gui thing in linux to launch emacs with gui

export org to md - https://emacs.stackexchange.com/questions/4279/exporting-from-org-mode-to-markdown
run this - M-x org-md-export-to-markdown
