#+title:      denote features
#+date:       [2023-11-25 Sat 21:23]
#+filetags:   :emacs:
#+identifier: 20231125T212326

[[file:20231125T211812--why-i-use-denote__emacs.org][Why I use Denote.]]

* Some features not to forget.

- Rename the files(denote-rename)
- Take pdf or any other file, rename it denote style - search for it later
- remove/add keywords
- quickly create notes
- modify the font matter to your liking
- use m% to search for notes with regular expressions

#+begin_src bash
  U - unmark all selections in dired

  %m

  t - toggle the mark
  k - kill unecessary
  g - close this
  v - view file quick
  q - quit
#+end_src

- have a list of "backlinks" that link to your current note
* Silos

Denote allows me to generate blog files quick and easy. They are all in the
same structure, do not require databse. I can link between them.

Default denote dir is Documents/org, but my denote dir is ~/GIT/notes. This is
where ALL my notes used to lie. When I decided to move the programming/work
related notes to a different directory, I had to make a "silo" in denote
terms - as described in https://protesilaos.com/emacs/denote.

instead of denote looking at my default denote dir when I create and manage
denote files, I had to specify another directory. I could do that by simply
creating a =.dir-locals.el= file in my new directory and add such content to
it:

#+begin_src emacs-lisp
  ;;; Directory Local Variables.  For more information evaluate:
  ;;;
  ;;;     (info "(emacs) Directory Variables")

  ((nil . ((denote-directory . default-directory))))
#+end_src

so now when denote is launched from THAT particular folder in which there is
this dir-locals.el file, it will know that It has to create notes in that
directory and not the default directory which I have specified in my init file,
which contains all my personal files.
