#+title: About
#+date: <2020-01-01 Sun 01:01>
#+description:
#+filetags:

- Graduated with a Bachelor degree in Architectural Technology
  Construction Management(ATCM) in a university in northern Denmark
  in 2017.
- Did [[https://www.youtube.com/@arvydasgasparaviciusphotog7250][landscape photography]] in my free time.
- I didn't find ATCM occupation exciting anymore so I [[https://www.instagram.com/this46383/][travelled the
  world]] for 2 years out of my savings.
- Coronavirus and empty pockets got me back to my home country
  Lithuania in 2021.
- Started to learn programming so I could work remotely.

* Linux :nonpost:

stuff from gvazdikelis about page

I am not about that 9-5 life doing things purely for the sake of
money, I want to feel some kind of meaning and see the usefulness in
my work and enjoy doing it, without feeling physically trapped in one
place in one area of expertise. I thought a lot about it in my free
time back here in Lithuania and I feel that programming and all that
stuff will allow me that. Work on a variety of different fields that I
might find enjoyable, do it from anywhere in the world and of course
having a lot of computer time.

Somehow hearing in the programming community that one of the best
operating systems for programming is Mac and Linux. I have a 7 year
old laptop, so I was thinking I will buy myself a mac and by like all
the other cool kids.

But instead I decided to save that chunk of money and work with my
acer as long as it allows me to, so I switched from being a lifetime
Windows user to being a Linux user. I like it so far. Like to find
people that explain Linux well and I started to notice that the
commands I am learning in Linux will be very much useful in various
environments around programming world. or w/e. So I guess I made a
right choice.

I am kind of a perfectionist, always trying to optimize everything in
my life and try to make good decisions from the start, so I thought
instead of nano text editor, which one is the best out there? After
lots of research I figured that Vim will be my choice, with bloat free
Artix Linux as my distribution and DWM windows manager to reduce the
strain on my old laptop as much as possible.

So there are lots of things to learn for a new person to programming.
Linux and all of that jazz (Luke Smith mostly), Python (Udemy course
with Jose Portilla), Machine Learning (Coursera course with Andrew
Ng), Web development to create my website (StudioWeb course with
Stefan Mischook).

Lots of things, yes, but I have a lot of free time and I am excited
about learning and applying in practice all of those things.

Alright, that is all about me. If you would like to give me some tips
or just get in touch, feel free to do so!

Best,

Arvydas
