#+title:      Status update 2021-05
#+date:       [2021-05-11 Tue 07:07]
#+filetags:   :statusupdate:
#+identifier: 20210511T070700
#+STARTUP:    overview

  Hey.

  You might not notice this, but it has been a while I have written here

  A few reasons being that I have put linux, vim, data science stuff on the
  shelf for a while.

  I offered my help to Julytes friend that is starting a sausage business and
  needed a website.

  I am using wordpress and building that. I have also noticed that I really
  need to have strong hmtl and css skills to be able to build a proper
  wordpress site. I also noticed I should know some php as well

  So during my time in Vilnius, it is 4th week now, I have been learning that.
  Most of the time got taken by figuring wordpress out, now since that is done,
  I am looking into hmtl and css and that is getting more clear.

  What I have learned now is how to color the things, got an idea how to work
  wiht the blocks and make stuff responsive in mobile. Tomorrow I think I will
  nail that with Steph's classe.

  You might think why don't I learn that right now - I'll tell you why. I am
  trying to divide my time a little. For now there are 3 parts. Python -
  Html/css - wordpress.

  As of now I have done the first two, time will be for wordpress.


    *Python*

    Dalykai kurie sekasi: karel done. Short input and math stuff is clear. What
    I want to learn: how to use external files/programs from python to start
    doing some useful stuff.

    *Html/css*

    Dalykai kurie sekasi: basic text editing, styling, etc. What I would like
    to know: how to work with those responsive design boxes, mobile layouts and
    etc.

    *Wordpess*

    Dalykai kurie sekasi: manual backups, elementor templates for various parts
    of the site (head, nav, footer, single page etc). What I would like to
    know: how to edit php files and find a way to show only what I want. Make
    website faster as well.
