#+title:      Little By Little
#+date:       [2021-06-04 Fri 11:30]
#+filetags:   :personal:productivity:
#+identifier: 20210604T113000
#+STARTUP:    overview

Just came back to the library after another "desinfection" thing for 30min, was
sitting in the square, sun was shining, was reading the Turing paper, eating
some ice cream, taking a walk.

As I was coming back to the library, I saw a guy that was literally burned by
the sun. I thought... Is it better for me to sit in the sun 10 minutes a day
and get an okey tan or sit once for 5 hours a day and get a sick tan..

Maybe its the same with learning to program. Why don't I learn little by little
daily, same like doing duolingo little by little daily, same like learning
guitar little by little daily...

At least I would be doing something, learning something little by little and
progressing little by little. Instead of picking a subject, going all in and
then burning out.

Little bit of Js, php, spaninsh, kali, python and etc daily...
