#+title:      Sim Card Back
#+date:       [2021-06-04 Fri 20:38]
#+filetags:   :personal:productivity:
#+identifier: 20210604T203800
#+STARTUP:    overview

Main reason to sit down and write this because Linux started behaving weirdly..
as I open a program (browser for example), it would show that it has been
opened, but I wouldn't see the window, couldn't interract with it.

It is a first time such thing has happened. I could open anki, could open
terminal and so on, but not a browser, not a "localbyflywheel" or "xampp".

And so I don't want to wait until tomorrow or for monday to fix this, I would
like to find a solution now so I can continue watching my downloaded tutorials
and follow them without any prblems...

Alright so hi again. Will make this quick and perhaps later will edit it more.

The situation now is this - it has been 5 days since I have taken my sim-card
with an internet from my smartphone and put it inside a flip phone that I
bought purely for this experiment and

Honestly I wanted it for a really long time.

Friday evening, I am sitting at home... you know what, instead of trying to fix
my linux and install arch and all that, why don't I just go get some sweet
stawberries, sit in the balcony and read a book in the sun...

Just came back to the computer after finishing reading the turing test... it
has been a while on my shelf, but probably wasn't the good time to read it yet,
didnt get much of it.

* Thoughts of week without 24/7 internet

I loved not being able to take picture of whateve moment I was in, I was able
to just be in it

I loved to be forced out of the library to take a break from "coding",
researching, because I would have never done that by myeself

I loved being dependent on the internet in the library, if I wanted to know
something new - I had to go there and connect to the internet.

I loved the bits of time that I got to do nothing. When I am bored.. I would
just sit down and look around, or most often I would pick up kindle and start
reading. Way better than mindless scrolling.

I loved the time that I had when I came back from the library after 6pm. I
would know okay I have 3-4 hours before I hit the bed, if there was nothing
urgent to do on my computer, then I would get up and move.

I loved that I took time to lear someting new.. I mean I would have done that
otherwise as well, but this time if I have one video that I downloaded, I
coudnt just skip it and watch a different one

As soon as I was bored, I had to stick with it, watch it until the end and
usually I was happy I did that becauce I learned something.

Same can go with all the things I didnt like. Sometimes yes, I wanted to have
my phone there to take and share that picture, yes I wanted to google an answer
to something and yeah sometimes some music would be nice..

I felt like I was back in Nepal Vipassana center... only calm moments around
me... not many distractions, mind is no constantly bombarded with music,
unlimited amount of information at my fingertips 24/7,

No music to get me distracted, no other kinds of bullshit... This kind of
lifestyle is my preferred actually.

But since I am not in a Vipassana center, I shouldn't totally restrict myself
from things.. Balance is everything, right? Why don't I take these lessons and
observations about myself and apply them

in my days that are ahead.. I am sure I will be more mindful.

Everything in moderation...

Last p tag. I will have to end here, going to insert the sim card into my
smartphone and connect to the interwebs once again, but this time more mindful.
21:49
