#+title:      python development in emacs
#+date:       [2023-11-26 Sun 01:47]
#+filetags:   :emacs:python:
#+identifier: 20231126T014740

* Dependencies

Simple python dev environment that does the job(without lsp)

Skybert paaiskinimas
https://www.youtube.com/watch?v=JmmTUIahB1U&ab_channel=SkybertHacks

Maybe dont even touch LSP FOR PYTHON.

simply create environment with pyvenv-create
then pyvenv-workon
then install the the needed packages that are described in elpy-config
pip3 install jedi autopep8 yapf black flake8 ipython importmagic

ipython - IPython is generally considered more feature-rich and
provides a more interactive and convenient experience. If you prefer
advanced features like tab completion, syntax highlighting, and
command history, IPython may be a better choice.

set this: basically is what you get when doing ctrl+ret on a piece of
code. looks more fancy, indeed, that python3 interpreter.

#+begin_src bash
(setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "-i --simple-prompt")
#+end_src

importmagic - Importmagic helps simplify the process by automatically analyzing
your code and suggesting or making changes to import statements based on the
modules and symbols used in your code. It can detect missing imports, remove
unused imports, and reorder existing imports according to a specified style or
convention.

if want auto-completion, warnings, navigation, IDE features like
rename - get eglot like here -
https://www.youtube.com/watch?v=JmmTUIahB1U&ab_channel=SkybertHacks

and that's it, lets get rolling.

have syntax highlights, corrections, completions, jumping to definitions etc.
very nice and simple.

LSP will be using for JS development and etc.

---------------------------------------------
LSP setup below(did not work)

+ LSP package and config
+ sudo apt install python3 (for python development)
+ apt install python3.10-venv (for python development)
+ Install a python language server - https://emacs-lsp.github.io/lsp-mode/page/lsp-pylsp/
+ berods dariau pip install "python-lsp-server[all]"
+ paskui sitas sudo apt install pipenv
+ create a python file
+ create a virtual environment with python3 -m venv <nameOfEnv> (or
  can do with pyvenv-create, then it will create virtual environment
  in ~/.virtualenvs folder)
+ Open emacs, do pyvenv-activate when you are inside the folder
  containing <nameOfEnv>
+ open terminal in emacs (shell, eshell, ansi-term, term) and do which
  python. You should see the <nameOfEnv> location. If you want to
  disable that env, do pyvenv-deactivate. Terminal will still have the
  <nameOfEnv> active, so might need to restart the terminal as well.
+ But then you will still get some sentinel error 1 errors
+ Lets see elpy config

---------------------------------------------------
more elpy docs:

  [2022-02-20 Sk] TUT: "Elpy" - various python modes for easier python
  programming. Installs various other packages as well. A few videos to help
  install elpy and customize.

  https://www.youtube.com/watch?v=0kuCeS-mfyc,
  https://www.youtube.com/watch?v=mflvdXKyA_g
  https://elpy.readthedocs.io/en/latest/index.html

  When using tab auto completion, click f1 and get the explanation in another
  buffer. Company doccumentation window. and of course more amazing [[https://gist.github.com/mahyaret/a64d209d482fc0f5eca707f12ccce146][shortcuts]]
  Here.

  If documentation suggestions get annoying - turn off eldoc mode

  INSTALL:
  1. sudo pip install elpy rope jedi
  1. add export PATH=$PATH:~/.local/bin to your .bashrc file and reload
     Emacs.
  2. should get a message asking something about RPC, click yes.
  3. then make sure jedi is installed in your system. others use flake8,
     others use jedi.. idk. zamansky and the guy from he tutorial video
     use jedi.
  4. do M-x elpy-config to see the config
  5. check your .emacs.d folder. if there is one called "elpy" and it is
     empty or something, do M-x elpy-rpc-restart. Folders will appear,
     packages will install. Then do elpy-config
  6. pip install flake8 - get to see more syntax checks. M-x elpy-config
     to confirm its installed

* Commands

lsp-doctor
lsp-install server

* virtual env

~/.virtualenvs/ - cia guli visos virtual env

- ijunk emacs ir iskart daryk pyvenv workon
- pip list(ar viso kompo info ziuri ar tik env environment)
- pyvenv-workon - create a virtual env in a folder
- pip list
- elpy config - susiinstallink visus packages
