#+title:      vscode
#+date:       [2023-11-25 Sat 18:10]
#+filetags:   :vscode:
#+identifier: 20231125T181008

* vscode
** vscode vs vim vs emacs lex fridman inspired
** try out evil mode...

it might be more practical to learn to use it instead of emacs bindings. when
you are in shell or when you are in vscode with vim plugin or when talking to
other programmers and when you are in a browser with vim extension for example.

** vscode shortcuts
- ~c-k c-t~ - choose theme
- syncing to other devices with github login in vs code...
- ~c-shift-p~ - ope command pallet
- ~f5~ - run and debug ANY file
- jupyter notebooks in vscode? what is it for
- ~c-k c-o~ - open a folder(opens up nautilus)
- ~shift+alt+click/up/down~ multiple cursors
- ~ctrl+shift+k~ - delete entire line
- ~f2~ - rename variable
- ~c+shift+i~ - format entire document
- ~c+k c+f~ - format selection
- ~c+shift+[]~ - fold unfold code
- type "if" or "try" and then select some sugeested completion snippet..
- emmet works just the same
- ~c-`~ open terminal
- ~c-,~ - open settings
- ~C-1, C-2, C-3~ - different windows
- file->autosave - autosaves every little change
- ~c-n~ - create new file
- live server/live preview - html/css editing on the fly
- ~c+shift+g~ git interface
- run auto detected tasks(google when its useful)
- ~c+k c+s~ customize shortcuts
- eslint extensions for smth many downloads
** vscode plugins
** VScode github real life examples
plugin name - IntelliCode API Usage Examples
** https://desktop.github.com/
** why vscode

ar mane stabdo emacs?

pycharm is like an 18 wheeler truck and emacs is like your comfortable
toyota - Guido

Vscode is great. Its like a home i can go back to when I'm lost. But
Emacs is an adventure - Guy on youtube

[[https://www.youtube.com/watch?v=G5mtQhWNezQ&ab_channel=LexClips][sita kalba lex su Guido]]

- lex (vscode now 20k hours emacs)
- python create Guide Van Rossum (VSCODE now, 30 years emacs)
- George hotz(vscode + vim)
** Trying out other editors

I think it really depends on what someone wants out of Emacs. The
thread the other day on people who use both had a pretty strong choir
of people who use Org-mode for note taking and VS Code for dev work,
which makes perfect sense to me; Emacs guaranteed itself a place in my
workflow with Org-mode.

I think if you're satisfied with Emacs for now and you can concretely
point to packages and functionality in Emacs that you would not know
how to recreate in VS Code out of the gate, I would say there's not a
ton of reason to switch to VS Code. I'm largely in the same boat, know
the basics of some front-end web-dev, occasionally play around with CL
and elisp, all non-professionally.

Compatibility with a hypothetical future team will be dependent on
that team, and at the same time many of the guides/tutorials for Emacs
I've read encourage learning other editors and how they work in case
you run into an employment situation that won't work with Emacs for
whatever reason. Seems like good practice.
** Reason

I think people overvalue this kind of thing. Vscode is going to be
around for quite a while. If you think it would improve your life, you
should use it. It might eventually go away in 15 years, but if it
does, you can spend a weekend switching to something else. That’s
hardly a reason to use a suboptimal tool until then. Of course, you
may prefer Emacs, and that’s fine too. Just saying, I think it’s
unwise to avoid an extremely healthy ecosystem and tool purely on the
grounds that it might not exist forever.
** Andrei karpathy emacs lex did it convince him
** automatic formatting with prettier
https://youtube.com/shorts/dDtueNAFELo?si=EDK6Ospk9N38QY_L
