#+title:      wsl installation
#+date:       [2023-11-28 Tue 16:53]
#+filetags:   :linux:windows:wsl:
#+identifier: 20231128T165324

Ok so at <2023-11-26 Sun> I was very much getting to know to wsl and
how to install it properly.

First reason - I finally decided to use emacs more so I could use
denote([[denote:20231125T211812][Why I use denote]]). For that of course I did not want to
override my already custom emacs config and notes file structure,
wanted to create a NEW WSL UBUNTU instance where I could experiment.

Second reason - I was getting gliches in my wsl ([[denote:20231128T164359][wsl glitches in gui
applications]]).


So while I was trying to solve the first thing, I found out about the
second thing and that led me to all this documentation below.



perdek i emacs note sita - https://superuser.com/questions/1126721/rebooting-ubuntu-on-windows-without-rebooting-windows

--------------------------------
* Installation instructions

first - windows install
install needed software - lightroom, powertoys(ctrl map), vscode, insomnia, github desktop, docker desktop etc

then install wsl:

can have multiple ubuntu versions or other distros on the same windows machine

in powershell run:

#+begin_src shell
  # see all repos available
  wsl --list
  # install the default repo
  wsl --install ubuntu (butinai prirasyk ubuntu)
  # install a custom repo version
  wsl --install -d Ubuntu-20.04
#+end_src

After your distro is installed, conform the version with:

#+begin_src bash
lsb_release -a
#+end_src

Now check "add remove programs" ar tikrai yra ubutntu, paziurek ar
virs 1gb uzima, paleisk ji.

setup terminal to be ubuntu. So when you open cmd you would also see
the ubuntu terminal.
After the installation ubuntu wsl make ubuntu profile in cmd ->
settings -> profiles - > new profile -> duplicate ubuntu profile

to install emacs now, follow - [[denote:20231128T131156][install emacs on linux]]
