#+title:      moving emacsd into dotfiles repo
#+date:       [2023-12-09 Sat 08:04]
#+filetags:   :emacs:
#+identifier: 20231209T080431
#+STARTUP:    overview

So today [2023-12-09 Sat] is a morning for configs.

Shell is not working properly(wrong time in wsl). I use tmux sometimes, I use
fish now(config will come also probably), I use vim sometimes, I want my bashrc
to look certain way... many config files and they are now all over the place on
different machines.

I need to have one repo for this.

What I did, because I did not want to lose the =.emacs.d= version history is
renamed that repo to =dotfiles=. Inside of that dotfiles directory I have
created .emacs.d folder content. I then git clone that folder into any location
on my machine and then link the .emacd.d folder to that git folder like such:

#+begin_src bash
  cd
  # source destination(your wanted new location)
  ln -s GIT/dotfiles/.emacs.d/ .emacs.d
#+end_src

and now when I launch emacs from anywhere inside my wsl, it looks into
=GIT/dotfiles/.emacs.d/= for my .emacs.d config files. Great.

Now in that =dotfiles= folder I can start putting other config files.

[2023-12-09 Sat 09:40] I have also created a [[denote:20231209T093750][new machine setup]] file in dotfiles
folder which will automatically allow you to configure the new machine. Great!
xoxo
